server:
  port: 8081

spring:
  application:
    name: seckill
  data:
    redis:
      host: localhost
      port: 6380
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 5000ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/seckill?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root123456
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.seckill: debug
    com.seckill.mapper: debug

performance:
  slow-threshold-ms: 1000
